### ISSUE TITLE
Filtering date fields

### ISSUE THREAD

**Issue by xeonva** [SynechronGit/ODataQueryHelper#2]
Hi,

First of all thank you for this project. I was in need of odata for MongoDb in .net core and your project solved most of my problems.
However, I don't know how to filter date fields. When I use $filter=date eq '2018-02-17' to filter date field, I get an error saying: "The binary operator Equal is not defined for the types 'System.DateTime' and 'System.String'."
I tried many options, date(2018-02-17), date('2018-02-17'), 2018-02-17, 2018-02-17T00:00:00, '2018-02-17T00:00:00' etc. Can you please help me with that?

Thanks.

**Comment by syn-sanket-mistry** [comment]
Try **date eq datetime'2018-12-31'**
